FROM openjdk:8-jdk-alpine
LABEL maintainer="Varun Reddy"
VOLUME /tmp
EXPOSE 3000
ARG JAR_FILE=target/zipcodeindicator-0.0.1-SNAPSHOT.jar
ADD {JAR_FILE} zipcodeindicator.jar

ENTRYPOINT ["java","-jar","zipcodeindicator.jar"]
